### ISSUE TITLE
Options is not working

### ISSUE THREAD

**Issue by tikn** [smurfy/cloud-zoom#12]
Options have no effect.
`$('.cloud-zoom, .cloud-zoom-gallery').CloudZoom({`
`position: 'inside',`
`gallerySwitchOnMouseOver: false`
`});`

**Comment by smurfy** [comment]
Did you try using the `rel` attribute for configuration instead? Its usually easier to use the markup.

Do you have a sample of your tries?

**Comment by tikn** [comment]
Just overide that options no modification.
