### ISSUE TITLE
Why not start from version 1.0.3 instead of 1.0.2?

### ISSUE THREAD

**Issue by lsolesen** [smurfy/cloud-zoom#7]
The 1.0.3 version can be downloaded from here: http://blog.belvg.com/cloud-zoom-jquery-plugin-v1-0-3-vs-v2-1.html

**Comment by smurfy** [comment]
My fork is quite old and i started it before 1.0.3 was out. I compared 1.0.2 and 1.0.3 a while back and just checked again, 1.0.3 brings no benefits compared to my fork.

Main change 1.0.3 over original 1.0.2 was some code cleaning (multiline changes) and modified blank.png behavior. 

The linked 1.0.3 version is also not compatible with newer jquery versions. (would be an easy fix tho)
